all:
	gcc server.c -o server
	gcc client.c -o client

two:
	gcc server2.c -o server
	gcc client2.c -o client

three:
	gcc server_badpackets.c -o server
	gcc client_badpackets.c -o client

four: 
	gcc newserver.c -o server
	gcc newclient.c -o client

clean:
	rm server
	rm client